/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddForm {
        "jwt": any;
    }
    interface ButtonComponent {
        "user_id": string;
    }
    interface FundsButton {
        "image": string;
    }
    interface MyComponent {
        "fetchData": () => Promise<any>;
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface OtpModal {
        "visible": boolean;
    }
    interface PlainModal {
        "visible": boolean;
    }
    interface RedeemForm {
        "jwt": any;
    }
    interface SummaryModal {
        "visible": boolean;
    }
    interface SwitchForm {
        "jwt": any;
        "show": boolean;
    }
    interface SwitchFundModal {
        "modalTitle": string;
        "visible": boolean;
    }
    interface SwitchMobile {
    }
    interface TermsModal {
        "visible": boolean;
    }
    interface UserComponent {
        "cssClass": string;
        "jwt": string;
        "valid": boolean;
    }
}
declare global {
    interface HTMLAddFormElement extends Components.AddForm, HTMLStencilElement {
    }
    var HTMLAddFormElement: {
        prototype: HTMLAddFormElement;
        new (): HTMLAddFormElement;
    };
    interface HTMLButtonComponentElement extends Components.ButtonComponent, HTMLStencilElement {
    }
    var HTMLButtonComponentElement: {
        prototype: HTMLButtonComponentElement;
        new (): HTMLButtonComponentElement;
    };
    interface HTMLFundsButtonElement extends Components.FundsButton, HTMLStencilElement {
    }
    var HTMLFundsButtonElement: {
        prototype: HTMLFundsButtonElement;
        new (): HTMLFundsButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLOtpModalElement extends Components.OtpModal, HTMLStencilElement {
    }
    var HTMLOtpModalElement: {
        prototype: HTMLOtpModalElement;
        new (): HTMLOtpModalElement;
    };
    interface HTMLPlainModalElement extends Components.PlainModal, HTMLStencilElement {
    }
    var HTMLPlainModalElement: {
        prototype: HTMLPlainModalElement;
        new (): HTMLPlainModalElement;
    };
    interface HTMLRedeemFormElement extends Components.RedeemForm, HTMLStencilElement {
    }
    var HTMLRedeemFormElement: {
        prototype: HTMLRedeemFormElement;
        new (): HTMLRedeemFormElement;
    };
    interface HTMLSummaryModalElement extends Components.SummaryModal, HTMLStencilElement {
    }
    var HTMLSummaryModalElement: {
        prototype: HTMLSummaryModalElement;
        new (): HTMLSummaryModalElement;
    };
    interface HTMLSwitchFormElement extends Components.SwitchForm, HTMLStencilElement {
    }
    var HTMLSwitchFormElement: {
        prototype: HTMLSwitchFormElement;
        new (): HTMLSwitchFormElement;
    };
    interface HTMLSwitchFundModalElement extends Components.SwitchFundModal, HTMLStencilElement {
    }
    var HTMLSwitchFundModalElement: {
        prototype: HTMLSwitchFundModalElement;
        new (): HTMLSwitchFundModalElement;
    };
    interface HTMLSwitchMobileElement extends Components.SwitchMobile, HTMLStencilElement {
    }
    var HTMLSwitchMobileElement: {
        prototype: HTMLSwitchMobileElement;
        new (): HTMLSwitchMobileElement;
    };
    interface HTMLTermsModalElement extends Components.TermsModal, HTMLStencilElement {
    }
    var HTMLTermsModalElement: {
        prototype: HTMLTermsModalElement;
        new (): HTMLTermsModalElement;
    };
    interface HTMLUserComponentElement extends Components.UserComponent, HTMLStencilElement {
    }
    var HTMLUserComponentElement: {
        prototype: HTMLUserComponentElement;
        new (): HTMLUserComponentElement;
    };
    interface HTMLElementTagNameMap {
        "add-form": HTMLAddFormElement;
        "button-component": HTMLButtonComponentElement;
        "funds-button": HTMLFundsButtonElement;
        "my-component": HTMLMyComponentElement;
        "otp-modal": HTMLOtpModalElement;
        "plain-modal": HTMLPlainModalElement;
        "redeem-form": HTMLRedeemFormElement;
        "summary-modal": HTMLSummaryModalElement;
        "switch-form": HTMLSwitchFormElement;
        "switch-fund-modal": HTMLSwitchFundModalElement;
        "switch-mobile": HTMLSwitchMobileElement;
        "terms-modal": HTMLTermsModalElement;
        "user-component": HTMLUserComponentElement;
    }
}
declare namespace LocalJSX {
    interface AddForm {
        "jwt"?: any;
        "onEmitter"?: (event: CustomEvent<any>) => void;
    }
    interface ButtonComponent {
        "user_id"?: string;
    }
    interface FundsButton {
        "image"?: string;
        "onOk"?: (event: CustomEvent<any>) => void;
        "onToken"?: (event: CustomEvent<any>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        "onCompleted"?: (event: CustomEvent<any>) => void;
    }
    interface OtpModal {
        "visible"?: boolean;
    }
    interface PlainModal {
        "visible"?: boolean;
    }
    interface RedeemForm {
        "jwt"?: any;
    }
    interface SummaryModal {
        "visible"?: boolean;
    }
    interface SwitchForm {
        "jwt"?: any;
        "onOk"?: (event: CustomEvent<any>) => void;
        "show"?: boolean;
    }
    interface SwitchFundModal {
        "modalTitle"?: string;
        "visible"?: boolean;
    }
    interface SwitchMobile {
    }
    interface TermsModal {
        "visible"?: boolean;
    }
    interface UserComponent {
        "cssClass"?: string;
        "jwt"?: string;
        "valid"?: boolean;
    }
    interface IntrinsicElements {
        "add-form": AddForm;
        "button-component": ButtonComponent;
        "funds-button": FundsButton;
        "my-component": MyComponent;
        "otp-modal": OtpModal;
        "plain-modal": PlainModal;
        "redeem-form": RedeemForm;
        "summary-modal": SummaryModal;
        "switch-form": SwitchForm;
        "switch-fund-modal": SwitchFundModal;
        "switch-mobile": SwitchMobile;
        "terms-modal": TermsModal;
        "user-component": UserComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-form": LocalJSX.AddForm & JSXBase.HTMLAttributes<HTMLAddFormElement>;
            "button-component": LocalJSX.ButtonComponent & JSXBase.HTMLAttributes<HTMLButtonComponentElement>;
            "funds-button": LocalJSX.FundsButton & JSXBase.HTMLAttributes<HTMLFundsButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "otp-modal": LocalJSX.OtpModal & JSXBase.HTMLAttributes<HTMLOtpModalElement>;
            "plain-modal": LocalJSX.PlainModal & JSXBase.HTMLAttributes<HTMLPlainModalElement>;
            "redeem-form": LocalJSX.RedeemForm & JSXBase.HTMLAttributes<HTMLRedeemFormElement>;
            "summary-modal": LocalJSX.SummaryModal & JSXBase.HTMLAttributes<HTMLSummaryModalElement>;
            "switch-form": LocalJSX.SwitchForm & JSXBase.HTMLAttributes<HTMLSwitchFormElement>;
            "switch-fund-modal": LocalJSX.SwitchFundModal & JSXBase.HTMLAttributes<HTMLSwitchFundModalElement>;
            "switch-mobile": LocalJSX.SwitchMobile & JSXBase.HTMLAttributes<HTMLSwitchMobileElement>;
            "terms-modal": LocalJSX.TermsModal & JSXBase.HTMLAttributes<HTMLTermsModalElement>;
            "user-component": LocalJSX.UserComponent & JSXBase.HTMLAttributes<HTMLUserComponentElement>;
        }
    }
}
